// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVUkVbJxD0IAu4TpaJpLjqQBJ6kePpDAE',
    appId: '1:736138084737:web:ed8697cc4c117e64f3e880',
    messagingSenderId: '736138084737',
    projectId: 'todo-app-50786',
    authDomain: 'todo-app-50786.firebaseapp.com',
    storageBucket: 'todo-app-50786.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ewPibPD_i-JvMB_hXz_7lEBFwVDF7rs',
    appId: '1:736138084737:android:51f29e27dd8b714ef3e880',
    messagingSenderId: '736138084737',
    projectId: 'todo-app-50786',
    storageBucket: 'todo-app-50786.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW18gP_VduTjqjwgnIk0dRA0ioKQOfX5M',
    appId: '1:736138084737:ios:a7cf41a66892c919f3e880',
    messagingSenderId: '736138084737',
    projectId: 'todo-app-50786',
    storageBucket: 'todo-app-50786.appspot.com',
    iosBundleId: 'com.example.todoMasterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW18gP_VduTjqjwgnIk0dRA0ioKQOfX5M',
    appId: '1:736138084737:ios:a7cf41a66892c919f3e880',
    messagingSenderId: '736138084737',
    projectId: 'todo-app-50786',
    storageBucket: 'todo-app-50786.appspot.com',
    iosBundleId: 'com.example.todoMasterFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVUkVbJxD0IAu4TpaJpLjqQBJ6kePpDAE',
    appId: '1:736138084737:web:a7f77ba4605d12e3f3e880',
    messagingSenderId: '736138084737',
    projectId: 'todo-app-50786',
    authDomain: 'todo-app-50786.firebaseapp.com',
    storageBucket: 'todo-app-50786.appspot.com',
  );

}